[general]
# import = [
#   "/opt/homebrew/lib/node_modules/alacritty-themes/themes/github_dark.toml"
# ]
import = [
  "~/.config/alacritty/colors.toml"
]

# import = [
#   "/opt/homebrew/lib/node_modules/alacritty-themes/themes/Material.toml"
# ]

[font]
size = 11

  [font.bold]
  family = "NotoSansM Nerd Font"
  # family = "Hack Nerd Font"
  style = "Bold"

  [font.bold_italic]
  family = "NotoSansM Nerd Font"
  # family = "Hack Nerd Font"
  style = "Bold Italic"

  [font.italic]
  family = "NotoSansM Nerd Font"
  # family = "Hack Nerd Font"
  style = "Italic"

  [font.normal]
  family = "NotoSansM Nerd Font"
  # family = "Hack Nerd Font"
  style = "Regular"

[window]
blur = true
opacity = 0.95

[terminal]
# shell = { program = "rm", args = ["$XDG_RUNTIME_DIR/alacritty.sock"]}
