[config]
reload_apps = true

[config.wallpaper]
command = 'swww'
arguments = ['img']
set = true

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~//.var/app/dev.vencord.Vesktop/config/vesktop/themes/midnight-discord.css'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship/starship.toml'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.ytmdeskop]
input_path = '~/.config/matugen/templates/ytmdesktop.css'
output_path = '~/.config/YouTube Music Desktop App/style.css'

[templates.chromium]
input_path = '~/.config/matugen/templates/chromium-colors.sh'
output_path = '~/.local/bin/scripts/window_manager/chromium_colors.sh'
post_hook = 'chmod 755 ~/.local/bin/scripts/window_manager/chromium_colors.sh; ~/.local/bin/scripts/window_manager/chromium_colors.sh'
# post_hook = '~/.local/bin/scripts/window_manager/apply_chromium.sh'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/Documents/Obsidian - Work/.obsidian/snippets/theme.css'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/btop.theme'

[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.var/app/io.github.Foldex.AdwSteamGtk/config/AdwSteamGtk/custom.css'
post_hook = 'flatpak run io.github.Foldex.AdwSteamGtk -i >/dev/null 2>&1'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.waybar_clock]
input_path = '~/.config/matugen/templates/waybar/clock.jsonc'
output_path = '~/.config/waybar/items/clock.jsonc'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/style/colors.css'
post_hook = 'pkill --signal SIGUSR2 waybar'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'
#
[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/color.kdl'

[templates.foot]
input_path = '~/.config/matugen/templates/foot.ini'
output_path = '~/.config/foot/theme.ini'
post_hook = 'pkill --signal SIGUSR1 foot'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

# Qt5
# [templates.qt5]
# input_path = '~/.config/matugen/templates/qtct-colors.conf'
# output_path = '~/.config/qt5ct/style-colors.conf'

# Qt6
[templates.qt6]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen-qt6ct.conf'

# Kvantum
[templates.kvantum]
input_path = '~/.config/matugen/templates/matugen.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

# Ly DM
[templates.ly]
input_path = '~/.config/matugen/templates/ly-dm.ini'
output_path = '~/.local/share/ly/config.ini'
